function pug_attr(t,e,n,r){if(e===!1||null==e||!e&&("class"===t||"style"===t))return"";if(e===!0)return" "+(r?t:t+'="'+t+'"');if("function"==typeof e.toISOString)e=e.toISOString();else if("string"!=typeof e&&(e=JSON.stringify(e),!n&&-1!==e.indexOf('"')))return" "+t+"='"+e.replace(/'/g,"&#39;")+"'";return n&&(e=pug_escape(e))," "+t+'="'+e+'"'}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(i){pug_rethrow(n,null,r)}var a=3,o=t.split("\n"),h=Math.max(r-a,0),s=Math.min(o.length,r+a),a=o.slice(h,s).map(function(n,e){var t=e+h+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+a+"\n\n"+n.message,n}function templatedetail(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {"pilotedatadetail.pug":".detailpopin(data-title=title)\n  .title\n  .close ×\n  = title\n  .support\n    .header\n      img(src='img\u002Ficon_support.png')\n      h4 OÙ\n    p= support\n  .access\n    .header\n      img(src='img\u002Ficon_access.png')\n      h4 COMMENT Y ACCÉDER\n    p= access\n    p\n      i= supportExampleWLinks\n  .accesseasiness\n    h4 FACILITÉ D'ACCÈS\n      img(src='img\u002Faccesseasiness_\" + info.accessEasiness + \".png')\n"};
;var locals_for_with = (locals || {});(function (access, support, supportExampleWLinks, title) {;pug_debug_line = 1;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv" + (" class=\"detailpopin\""+pug_attr("data-title", title, true, false)) + "\u003E";
;pug_debug_line = 2;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"title\"\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 3;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"close\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "×\u003C\u002Fdiv\u003E";
;pug_debug_line = 4;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = title) ? "" : pug_interp));
;pug_debug_line = 5;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"support\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"header\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cimg src=\"img\u002Ficon_support.png\"\u002F\u003E";
;pug_debug_line = 8;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Ch4\u003E";
;pug_debug_line = 8;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "OÙ\u003C\u002Fh4\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 9;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 9;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = support) ? "" : pug_interp)) + "\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 10;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"access\"\u003E";
;pug_debug_line = 11;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"header\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cimg src=\"img\u002Ficon_access.png\"\u002F\u003E";
;pug_debug_line = 13;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Ch4\u003E";
;pug_debug_line = 13;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "COMMENT Y ACCÉDER\u003C\u002Fh4\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 14;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 14;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = access) ? "" : pug_interp)) + "\u003C\u002Fp\u003E";
;pug_debug_line = 15;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 16;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Ci\u003E";
;pug_debug_line = 16;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = supportExampleWLinks) ? "" : pug_interp)) + "\u003C\u002Fi\u003E\u003C\u002Fp\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cdiv class=\"accesseasiness\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Ch4\u003E";
;pug_debug_line = 18;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "FACILITÉ D'ACCÈS";
;pug_debug_line = 19;pug_debug_filename = "pilotedatadetail.pug";
pug_html = pug_html + "\u003Cimg src=\"img\u002Faccesseasiness_&quot; + info.accessEasiness + &quot;.png\"\u002F\u003E\u003C\u002Fh4\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";}.call(this,"access" in locals_for_with?locals_for_with.access:typeof access!=="undefined"?access:undefined,"support" in locals_for_with?locals_for_with.support:typeof support!=="undefined"?support:undefined,"supportExampleWLinks" in locals_for_with?locals_for_with.supportExampleWLinks:typeof supportExampleWLinks!=="undefined"?supportExampleWLinks:undefined,"title" in locals_for_with?locals_for_with.title:typeof title!=="undefined"?title:undefined));} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}